import jsPDF from "jspdf";
import QRCode from "qrcode";

const generateTicket = async (booking) => {

  const doc = new jsPDF();

  // Background Header
  doc.setFillColor(6, 182, 212);
  doc.rect(0, 0, 210, 40, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);

  doc.text(
    "EVENTHUB TICKET",
    55,
    25
  );

  doc.setTextColor(0, 0, 0);

  // Ticket Details

  doc.setFontSize(18);

  doc.text(
    booking.event?.title || "Event",
    20,
    60
  );

  doc.setFontSize(12);

  doc.text(
    `Booking ID: ${booking._id}`,
    20,
    80
  );

  doc.text(
    `Quantity: ${booking.quantity}`,
    20,
    95
  );

  doc.text(
    `Amount: ₹${booking.totalAmount}`,
    20,
    110
  );

  doc.text(
    `Status: ${booking.paymentStatus}`,
    20,
    125
  );

  doc.text(
    `Booked On: ${new Date(
      booking.createdAt
    ).toLocaleDateString()}`,
    20,
    140
  );

  // QR Data

  const qrData = `
Booking ID: ${booking._id}
Event: ${booking.event?.title}
Quantity: ${booking.quantity}
`;

  const qrImage =
    await QRCode.toDataURL(
      qrData
    );

  doc.addImage(
    qrImage,
    "PNG",
    130,
    70,
    50,
    50
  );

  doc.setFontSize(10);

  doc.text(
    "Scan QR for ticket verification",
    120,
    130
  );

  // Footer

  doc.setDrawColor(200);
  doc.line(
    20,
    160,
    190,
    160
  );

  doc.text(
    "Generated by EventHub",
    20,
    175
  );

  doc.save(
    `ticket-${booking._id}.pdf`
  );

};

export default generateTicket;